version: '3'

secrets:
  db-postgres-password:
    file: ./docker/secrets/postgres

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - APP_ENV=dev
    working_dir: /code
    env_file:
      - .env
    environment:
      DATABASE_PASSWORD_FILE: /run/secrets/db-postgres-password
      COMPOSER_MEMORY_LIMIT: -1
    volumes:
      - ./:/code:delegated,rw
    secrets:
      - db-postgres-password

  db:
    image: postgres:${POSTGRES_VERSION}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db-postgres-password
    secrets:
      - db-postgres-password
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  nginx:
    image: nginx:latest
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/code

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
